// useLionIsochrones.ts
// Loads pre-tiled MVT isochrones from /public/tiles/{z}/{x}/{y}.mvt
// Generated by precompute_isochrones.py (res 14, ~16m hex) + tippecanoe
// This hook only exports the type — MVTLayer handles fetching directly in Map.tsx

export interface IsochroneFeatureProps {
  h3:              string
  walkBand:        5 | 10 | 15
  walkabilityMult: number
  coverageCount:   number
  stopTypes:       string   // comma-separated e.g. "bus,citibike,subway"
  hasSubway:       number   // 1 | 0
  hasBus:          number
  hasCitibike:     number
}
